import type { MenuCategory } from "@/lib/types";

export const fallbackMenu: MenuCategory[] = [
  {
    id: "cat-drinks",
    name: "Cool Drinks",
    slug: "drinks",
    sort_order: 1,
    items: [
      {
        id: "coke",
        category_id: "cat-drinks",
        name: "Coke",
        slug: "coke",
        description: "",
        price_paise: 2000,
        icon: "water_drop",
        image_url:
          "https://images.pexels.com/photos/25291886/pexels-photo-25291886.jpeg?cs=srgb&dl=pexels-olenkabohovyk-25291886.jpg&fm=jpg",
        is_featured: false,
        is_active: true,
        sort_order: 1,
        prep_time_mins: 1,
      },
    ],
  },
  {
    id: "cat-snacks",
    name: "Snacks",
    slug: "snacks",
    sort_order: 2,
    items: [
      {
        id: "maggi",
        category_id: "cat-snacks",
        name: "Maggi",
        slug: "maggi",
        description: "",
        price_paise: 3000,
        icon: "ramen_dining",
        image_url:
          "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1200&q=80",
        is_featured: false,
        is_active: true,
        sort_order: 1,
        prep_time_mins: 8,
      },
      {
        id: "single-omelette",
        category_id: "cat-snacks",
        name: "Single Egg Omelette",
        slug: "single-omelette",
        description: "",
        price_paise: 2000,
        icon: "egg",
        image_url:
          "https://tse1.mm.bing.net/th/id/OIP.hnWK7pz-awMn0-hbP0AU2QHaLH?pid=Api&P=0&h=180",
        is_featured: false,
        is_active: true,
        sort_order: 2,
        prep_time_mins: 6,
      },
      {
        id: "double-omelette",
        category_id: "cat-snacks",
        name: "Double Egg Omelette",
        slug: "double-omelette",
        description: "",
        price_paise: 3000,
        icon: "egg",
        image_url:
          "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/06/egg-oats-omelette.jpg",
        is_featured: false,
        is_active: true,
        sort_order: 3,
        prep_time_mins: 7,
      },
      {
        id: "bread-omelette",
        category_id: "cat-snacks",
        name: "Bread Omelette",
        slug: "bread-omelette",
        description: "",
        price_paise: 4000,
        icon: "breakfast_dining",
        image_url:
          "https://tse4.mm.bing.net/th/id/OIP.dAAXxm2FVTAOBgcDqnyOLAHaHa?pid=Api&P=0&h=180",
        is_featured: true,
        is_active: true,
        sort_order: 4,
        prep_time_mins: 7,
      },
      {
        id: "vada-pav",
        category_id: "cat-snacks",
        name: "Vada Pav",
        slug: "vada-pav",
        description: "",
        price_paise: 2000,
        icon: "lunch_dining",
        image_url:
          "https://tse1.mm.bing.net/th/id/OIP.rYFnUL1PfPfAjDiV6r2yWgHaHa?pid=Api&P=0&h=180",
        is_featured: false,
        is_active: true,
        sort_order: 5,
        prep_time_mins: 4,
      },
      {
        id: "samosa",
        category_id: "cat-snacks",
        name: "Samosa",
        slug: "samosa",
        description: "",
        price_paise: 2000,
        icon: "bakery_dining",
        image_url:
          "https://tse1.mm.bing.net/th/id/OIP.gzfLita-jg6Uhv0TfA8RZgHaHa?pid=Api&P=0&h=180",
        is_featured: false,
        is_active: true,
        sort_order: 6,
        prep_time_mins: 3,
      },
      {
        id: "veg-sandwich",
        category_id: "cat-snacks",
        name: "Veg Sandwich",
        slug: "veg-sandwich",
        description: "",
        price_paise: 3000,
        icon: "breakfast_dining",
        image_url:
          "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80",
        is_featured: false,
        is_active: true,
        sort_order: 7,
        prep_time_mins: 5,
      },
    ],
  },
];
