import type { MenuCategory } from "@/lib/types";

export const fallbackMenu: MenuCategory[] = [
  {
    id: "cat-drinks",
    name: "Drinks",
    slug: "drinks",
    sort_order: 1,
    items: [
      {
        id: "tea",
        category_id: "cat-drinks",
        name: "Tea",
        slug: "tea",
        description: "Freshly brewed tea to kickstart your class break.",
        price_paise: 1000,
        icon: "coffee",
        image_url: null,
        is_featured: false,
        is_active: true,
        sort_order: 1,
        prep_time_mins: 3,
      },
      {
        id: "coffee",
        category_id: "cat-drinks",
        name: "Coffee",
        slug: "coffee",
        description: "Strong and hot, made for quick campus energy.",
        price_paise: 1500,
        icon: "local_cafe",
        image_url: null,
        is_featured: false,
        is_active: true,
        sort_order: 2,
        prep_time_mins: 4,
      },
      {
        id: "coke",
        category_id: "cat-drinks",
        name: "Coke",
        slug: "coke",
        description: "Ice-cold fizzy refreshment for the afternoon rush.",
        price_paise: 2000,
        icon: "water_drop",
        image_url: null,
        is_featured: false,
        is_active: true,
        sort_order: 3,
        prep_time_mins: 1,
      },
    ],
  },
  {
    id: "cat-snacks",
    name: "Snacks",
    slug: "snacks",
    sort_order: 2,
    items: [
      {
        id: "maggi",
        category_id: "cat-snacks",
        name: "Maggi",
        slug: "maggi",
        description: "The classic college comfort bowl. Hot, quick, and spicy.",
        price_paise: 3000,
        icon: "ramen_dining",
        image_url:
          "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1200&q=80",
        is_featured: true,
        is_active: true,
        sort_order: 1,
        prep_time_mins: 8,
      },
      {
        id: "omelette",
        category_id: "cat-snacks",
        name: "Omelette",
        slug: "omelette",
        description: "Soft, hot omelette folded fresh on the tawa.",
        price_paise: 2500,
        icon: "egg",
        image_url: null,
        is_featured: false,
        is_active: true,
        sort_order: 2,
        prep_time_mins: 6,
      },
      {
        id: "bread-omelette",
        category_id: "cat-snacks",
        name: "Bread Omelette",
        slug: "bread-omelette",
        description: "A loaded hostel favorite that eats like a full meal.",
        price_paise: 4000,
        icon: "breakfast_dining",
        image_url: null,
        is_featured: false,
        is_active: true,
        sort_order: 3,
        prep_time_mins: 7,
      },
    ],
  },
];
